const METRO_ISTANBUL_STATIONS = {
    'M1': [
        { no: 1, name: 'Yenikapı' },
        { no: 2, name: 'Aksaray' },
        { no: 3, name: 'Emniyet-Fatih' },
        { no: 4, name: 'Topkapı-Ulubatlı' },
        { no: 5, name: 'Bayrampaşa-Maltepe' },
        { no: 6, name: 'Sağmalcılar' },
        { no: 7, name: 'Kocatepe' },
        { no: 8, name: 'Otogar' },
        { no: 9, name: 'Terazidere' },
        { no: 10, name: 'Davutpaşa-YTÜ' },
        { no: 11, name: 'Merter' },
        { no: 12, name: 'Zeytinburnu' },
        { no: 13, name: 'Bakırköy-İncirli' },
        { no: 14, name: 'Bahçelievler' },
        { no: 15, name: 'Ataköy-Şirinevler' },
        { no: 16, name: 'Yenibosna' },
        { no: 17, name: 'DTM-İstanbul Fuar Merkezi' },
        { no: 18, name: 'Atatürk Havalimanı' },
        { no: 19, name: 'Esenler' },
        { no: 20, name: 'Menderes' },
        { no: 21, name: 'Üçyüzlü' },
        { no: 22, name: 'Bağcılar Meydan' },
        { no: 23, name: 'Kirazlı' }
    ],
    'M2': [
        { no: 1, name: 'Yenikapı' },
        { no: 2, name: 'Vezneciler-İstanbul Ü.' },
        { no: 3, name: 'Haliç' },
        { no: 4, name: 'Şişhane' },
        { no: 5, name: 'Taksim' },
        { no: 6, name: 'Osmanbey' },
        { no: 7, name: 'Şişli-Mecidiyeköy' },
        { no: 8, name: 'Gayrettepe' },
        { no: 9, name: 'Levent' },
        { no: 10, name: '4.Levent' },
        { no: 11, name: 'Sanayi Mahallesi' },
        { no: 12, name: 'İTÜ-Ayazağa' },
        { no: 13, name: 'Atatürk Oto Sanayi' },
        { no: 14, name: 'Darüşşafaka' },
        { no: 15, name: 'Hacıosman' },
        { no: 16, name: 'Seyrantepe' }
    ],
    'M3': [
        { no: 1, name: 'Bakırköy Sahil' },
        { no: 2, name: 'İncirli' },
        { no: 3, name: 'Haznedar' },
        { no: 4, name: 'İlkyuva' },
        { no: 5, name: 'Yıldıztepe' },
        { no: 6, name: 'Molla Gürani' },
        { no: 7, name: 'Kirazlı' },
        { no: 8, name: 'Yenimahalle' },
        { no: 9, name: 'Mahmutbey' },
        { no: 10, name: 'İSTOÇ' },
        { no: 11, name: 'İkitelli Sanayi' },
        { no: 12, name: 'Turgut Özal' },
        { no: 13, name: 'Siteler' },
        { no: 14, name: 'Başak Konutları' },
        { no: 15, name: 'MetroKent' },
        { no: 16, name: 'Onurkent' },
        { no: 17, name: 'Şehir Hastanesi' },
        { no: 18, name: 'Toplu Konutlar' },
        { no: 19, name: 'Kayaşehir Merkez' }
    ],
    'M4': [
        { no: 1, name: 'Kadıköy' },
        { no: 2, name: 'Ayrılık Çeşmesi' },
        { no: 3, name: 'Acıbadem' },
        { no: 4, name: 'Ünalan' },
        { no: 5, name: 'Göztepe' },
        { no: 6, name: 'Yenisahra' },
        { no: 7, name: 'Kozyatağı' },
        { no: 8, name: 'Bostancı' },
        { no: 9, name: 'Küçükyalı' },
        { no: 10, name: 'Maltepe' },
        { no: 11, name: 'Huzurevi' },
        { no: 12, name: 'Gülsuyu' },
        { no: 13, name: 'Esenkent' },
        { no: 14, name: 'Hastane-Adliye' },
        { no: 15, name: 'Soğanlık' },
        { no: 16, name: 'Kartal' },
        { no: 17, name: 'Yakacık-Adnan Kahveci' },
        { no: 18, name: 'Pendik' },
        { no: 19, name: 'Tavşantepe' },
        { no: 20, name: 'Fevzi Çakmak-Hastane' },
        { no: 21, name: 'Yayalar-Şeyhli' },
        { no: 22, name: 'Kurtköy' },
        { no: 23, name: 'Sabiha Gökçen Havalimanı' }
    ],
    'M5': [
        { no: 1, name: 'Üsküdar' },
        { no: 2, name: 'Fıstıkağacı' },
        { no: 3, name: 'Bağlarbaşı' },
        { no: 4, name: 'Altunizade' },
        { no: 5, name: 'Kısıklı' },
        { no: 6, name: 'Bulgurlu' },
        { no: 7, name: 'Ümraniye' },
        { no: 8, name: 'Çarşı' },
        { no: 9, name: 'Yamanevler' },
        { no: 10, name: 'Çakmak' },
        { no: 11, name: 'Ihlamurkuyu' },
        { no: 12, name: 'Altınşehir' },
        { no: 13, name: 'İmam Hatip Lisesi' },
        { no: 14, name: 'Dudullu' },
        { no: 15, name: 'Necip Fazıl' },
        { no: 16, name: 'Çekmeköy' },
        { no: 17, name: 'Meclis' },
        { no: 18, name: 'Sarıgazi' },
        { no: 19, name: 'Sancaktepe' },
        { no: 20, name: 'Sancaktepe Şehir Hastanesi' },
        { no: 21, name: 'Samandıra Merkez' }
    ],
    'M6': [
        { no: 1, name: 'Levent' },
        { no: 2, name: 'Nispetiye' },
        { no: 3, name: 'Etiler' },
        { no: 4, name: 'Boğaziçi Üni./Hisarüstü' }
    ],
    'M7': [
        { no: 1, name: 'Yıldız' },
        { no: 2, name: 'Fulya' },
        { no: 3, name: 'Mecidiyeköy' },
        { no: 4, name: 'Çağlayan' },
        { no: 5, name: 'Kağıthane' },
        { no: 6, name: 'Nurtepe' },
        { no: 7, name: 'Alibeyköy' },
        { no: 8, name: 'Çırçır' },
        { no: 9, name: 'Veysel Karani-Akşemsettin' },
        { no: 10, name: 'Yeşilpınar' },
        { no: 11, name: 'Kazım Karabekir' },
        { no: 12, name: 'Yenimahalle' },
        { no: 13, name: 'Karadeniz Mahallesi' },
        { no: 14, name: 'Giyimkent-Tekstilkent' },
        { no: 15, name: 'Oruç Reis' },
        { no: 16, name: 'Göztepe Mahallesi' },
        { no: 17, name: 'Mahmutbey' }
    ],
    'M8': [
        { no: 1, name: 'Bostancı' },
        { no: 2, name: 'Emin Ali Paşa' },
        { no: 3, name: 'Ayşekadın' },
        { no: 4, name: 'Kozyatağı' },
        { no: 5, name: 'Küçükbakkalköy' },
        { no: 6, name: 'İçerenköy' },
        { no: 7, name: 'Kayışdağı' },
        { no: 8, name: 'Mevlana' },
        { no: 9, name: 'İMES' },
        { no: 10, name: 'MODOKO-Keyap' },
        { no: 11, name: 'Dudullu' },
        { no: 12, name: 'Parseller' }
    ],
    'M9': [
        { no: 1, name: 'Ataköy' },
        { no: 2, name: 'Yenibosna' },
        { no: 3, name: 'Çobançeşme' },
        { no: 4, name: 'İhlas Yuva' },
        { no: 5, name: 'Doğu Sanayi' },
        { no: 6, name: 'Mimar Sinan' },
        { no: 7, name: '15 Temmuz' },
        { no: 8, name: 'Halkalı Caddesi' },
        { no: 9, name: 'Atatürk Mahallesi' },
        { no: 10, name: 'Bahariye' },
        { no: 11, name: 'Masko' },
        { no: 12, name: 'İkitelli Sanayi' },
        { no: 13, name: 'Ziya Gökalp Mahallesi' },
        { no: 14, name: 'Olimpiyat' }
    ],
    'T1': [
        { no: 1, name: 'Bağcılar' },
        { no: 2, name: 'Güneştepe' },
        { no: 3, name: 'Yavuzselim' },
        { no: 4, name: 'Soğanlı' },
        { no: 5, name: 'Akıncılar' },
        { no: 6, name: 'Güngören' },
        { no: 7, name: 'Merter Tekstil Merkezi' },
        { no: 8, name: 'Mehmet Akif' },
        { no: 9, name: 'Zeytinburnu' },
        { no: 10, name: 'Mithatpaşa' },
        { no: 11, name: 'Seyitnizam-Akşemsettin' },
        { no: 12, name: 'Merkezefendi' },
        { no: 13, name: 'Cevizlibağ-AÖY' },
        { no: 14, name: 'Topkapı' },
        { no: 15, name: 'Pazartekke' },
        { no: 16, name: 'Çapa-Şehremini' },
        { no: 17, name: 'Fındıkzade' },
        { no: 18, name: 'Haseki' },
        { no: 19, name: 'Yusufpaşa' },
        { no: 20, name: 'Aksaray' },
        { no: 21, name: 'Laleli-İstanbul Ü.' },
        { no: 22, name: 'Beyazıt-Kapalıçarşı' },
        { no: 23, name: 'Çemberlitaş' },
        { no: 24, name: 'Sultanahmet' },
        { no: 25, name: 'Gülhane' },
        { no: 26, name: 'Sirkeci' },
        { no: 27, name: 'Eminönü' },
        { no: 28, name: 'Karaköy' },
        { no: 29, name: 'Tophane' },
        { no: 30, name: 'Fındıklı-Mimar Sinan Ü.' },
        { no: 31, name: 'Kabataş' }
    ],
    'T4': [
        { no: 1, name: 'Topkapı' },
        { no: 2, name: 'Fetihkapı' },
        { no: 3, name: 'Vatan' },
        { no: 4, name: 'Edirnekapı' },
        { no: 5, name: 'Şehitlik' },
        { no: 6, name: 'Demirkapı' },
        { no: 7, name: 'Topçular' },
        { no: 8, name: 'Rami' },
        { no: 9, name: 'Uluyol Bereç' },
        { no: 9, name: 'Uluyol' },
        { no: 9, name: 'Bereç' },
        { no: 10, name: 'Sağmalcılar' },
        { no: 11, name: 'Bosna-Çukurçeşme' },
        { no: 12, name: 'Ali Fuat Başgil' },
        { no: 13, name: 'Taşköprü' },
        { no: 14, name: 'Karadeniz' },
        { no: 15, name: 'Metris' },
        { no: 15, name: 'Kiptaş Venezia' },
        { no: 15, name: 'Kiptaş - Venezia' },
        { no: 15, name: 'Kiptaş-Venezia' },
        { no: 16, name: 'Cumhuriyet Mah.' },
        { no: 17, name: '50. Yıl-Baştabya' },
        { no: 18, name: 'Hacı Şükrü' },
        { no: 19, name: 'Yeni Mahalle' },
        { no: 20, name: 'Sultançiftliği' },
        { no: 21, name: 'Cebeci' },
        { no: 22, name: 'Mescid-i Selam' },
        { no: 23, name: 'Habibler Yerleşke' },
        { no: 24, name: 'Habibler Depo' }
    ],
    'T5': [
        { no: 1, name: 'Eminönü' },
        { no: 2, name: 'Küçükpazar' },
        { no: 3, name: 'Cibali' },
        { no: 4, name: 'Fener' },
        { no: 5, name: 'Balat' },
        { no: 6, name: 'Ayvansaray' },
        { no: 7, name: 'Feshane' },
        { no: 8, name: 'Eyüpsultan Teleferik' },
        { no: 9, name: 'Eyüpsultan Devlet Hast.' },
        { no: 10, name: 'Silahtarağa' },
        { no: 11, name: 'Üniversite' },
        { no: 12, name: 'Alibeyköy Merkez' },
        { no: 13, name: 'Alibeyköy Metro' },
        { no: 14, name: 'Alibeyköy Cep Otogarı' }
    ],
    'F1': [
        { no: 1, name: 'Taksim' },
        { no: 2, name: 'Kabataş' }
    ],
    'TF1': [
        { no: 1, name: 'Maçka' },
        { no: 2, name: 'Taşkışla' }
    ],
    'TF2': [
        { no: 1, name: 'Eyüp' },
        { no: 2, name: 'Piyer Loti' }
    ]
};

const DEFAULT_STATIONS = {};
const DEFAULT_STATION_NUMBERS = {};
Object.entries(METRO_ISTANBUL_STATIONS).forEach(([line, stArray]) => {
    DEFAULT_STATIONS[line] = stArray.map(s => s.name);
    DEFAULT_STATION_NUMBERS[line] = {};
    stArray.forEach(s => { DEFAULT_STATION_NUMBERS[line][s.name] = s.no; });
});
